api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: ":443"
metrics:
  prometheus: {}
serversTransport:
  insecureSkipVerify: true
providers:
  # docker:
  #   endpoint: "unix:///var/run/docker.sock"
  #   exposedByDefault: false
  file:
    directory: /providers
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      email: johndoe@example.com # Cloudflare email address goes here
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"