---
api:
  dashboard: true
  debug: true
  insecure: true

log:
  level: DEBUG

accessLog: {}

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

metrics:
  prometheus: {}

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    directory: /providers
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: email@example.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
