---
http:
  middlewares:
    pve-headers: # Headers to add to proxmox requests - makes sure novnc works
      headers:
        frameDeny: true
        sslRedirect: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    allowlist: # Whitelist for internal networks, if applied denies all other traffic
      ipAllowList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.0.0.0/8"

    proxmox: # Proxmox node chain - chain can be used to add multiple middlewares to a router
      chain:
        middlewares:
          - allowlist
          - pve-headers
