---
http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    pve-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.0.0.0/8"

    # idrac:
    #   headers:
    #     frameDeny: true
    #     browserXssFilter: true
    #     forceSTSHeader: true
    #     stsIncludeSubdomains: true
    #     stsSeconds: 15552000
    #     customFrameOptionsValue: SAMEORIGIN
    #     customRequestHeaders:
    #       X-Forwarded-Proto: https

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers